language: objective-c
osx_image: xcode7.2

before_script:
- xcrun simctl list
- SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6 (9.2) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")

script:
- echo $SIMULATOR_ID
- open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
- set -o pipefail
- xcodebuild -project Lensy.xcodeproj -scheme Lensy-iOS test -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" | xcpretty -c
- xcodebuild -project Lensy.xcodeproj -scheme Lensy-Mac test -sdk macosx | xcpretty -c
- pod lib lint --quick

after_success:
- bash <(curl -s https://codecov.io/bash)
